// <auto-generated />
namespace CommunityServiceProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddPendingModelChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPendingModelChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202610040034058_AddPendingModelChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
