// <auto-generated />
namespace CommunityServiceProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddTechnicianFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTechnicianFields));
        
        string IMigrationMetadata.Id
        {
            get { return "202608221730105_AddTechnicianFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
