// <auto-generated />
namespace CommunityServiceProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class AddWards111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddWards111));
        
        string IMigrationMetadata.Id
        {
            get { return "202610060248394_AddWards111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
