using System;
using System.Data.Entity;
using System.Linq;
using CommunityServiceProject.Models;
using CommunityServiceProject.ViewModels;
using System.Web.Mvc;

namespace CommunityServiceProject.Controllers
{
    public class CitizenFinancialController : Controller
    {
        private readonly Community db = new Community();


        // ============================================================
        // US153 - VIEW PAYMENT RECEIPT
        // ============================================================

        [HttpGet]
        public ActionResult Receipt(int id)
        {
            if (Session["CitizenID"] == null)
            {
                return RedirectToAction(
                    "Index",
                    "Login");
            }

            int citizenId =
                (int)Session["CitizenID"];


            var payment =
                db.Payments
                    .Include("Citizen")
                    .Include("Invoice.MunicipalServiceRequest.ServiceType")
                    .FirstOrDefault(p =>
                        p.PaymentID == id &&
                        p.CitizenID == citizenId);


            if (payment == null)
            {
                return HttpNotFound();
            }


            if (payment.Status != PaymentStatus.Successful)
            {
                TempData["ErrorMessage"] =
                    "A payment receipt is only available for successful payments.";

                return RedirectToAction(
                    "Details",
                    "MunicipalServiceRequest",
                    new
                    {
                        id = payment.Invoice != null &&
                             payment.Invoice.MunicipalServiceRequest != null
                            ? payment.Invoice.MunicipalServiceRequest.MunicipalServiceRequestID
                            : 0
                    });
            }


            if (payment.Invoice == null ||
                payment.Invoice.MunicipalServiceRequest == null)
            {
                TempData["ErrorMessage"] =
                    "The invoice linked to this payment could not be found.";

                return RedirectToAction(
                    "Dashboard",
                    "Citizen");
            }


            var receipt =
                db.Receipts
                    .FirstOrDefault(r =>
                        r.PaymentID == payment.PaymentID);


            if (receipt == null)
            {
                TempData["ErrorMessage"] =
                    "The payment was successful, but the receipt has not yet been generated by the Finance Officer.";

                return RedirectToAction(
                    "Details",
                    "MunicipalServiceRequest",
                    new
                    {
                        id =
                            payment.Invoice
                                .MunicipalServiceRequest
                                .MunicipalServiceRequestID
                    });
            }


            var request =
                payment.Invoice.MunicipalServiceRequest;

            var service =
                request.ServiceType;


            var model =
                new PaymentReceiptViewModel
                {
                    ReceiptID =
                        receipt.ReceiptID,

                    ReceiptNumber =
                        receipt.ReceiptNumber,

                    IssueDate =
                        receipt.IssueDate,

                    TransactionReference =
                        payment.TransactionReference,

                    InvoiceNumber =
                        payment.Invoice.InvoiceNumber,

                    RequestReference =
                        request.ReferenceNumber,

                    CitizenName =
                        payment.Citizen != null
                            ? payment.Citizen.FirstName +
                              " " +
                              payment.Citizen.LastName
                            : "Citizen",

                    ServiceName =
                        service != null
                            ? service.ServiceName
                            : "Municipal Service",

                    PaymentMethod =
                        payment.PaymentMethod,

                    PaymentDate =
                        payment.PaymentDate,

                    PaymentStatus =
                        payment.Status.ToString(),

                    AmountPaid =
                        payment.Amount,

                    InvoiceAmount =
                        payment.Invoice.Amount,

                    RemainingBalance =
                        payment.Invoice.Balance,

                    InvoiceStatus =
                        payment.Invoice.Status.ToString()
                };


            return View(model);
        }


        // ============================================================
        // US153 - VIEW RECEIPT FROM REQUEST DETAILS
        // ============================================================

        [HttpGet]
        public ActionResult ReceiptFromRequest(int id)
        {
            if (Session["CitizenID"] == null)
            {
                return RedirectToAction(
                    "Index",
                    "Login");
            }

            int citizenId =
                (int)Session["CitizenID"];


            var request =
                db.MunicipalServiceRequests
                    .Include("ServiceType")
                    .FirstOrDefault(r =>
                        r.MunicipalServiceRequestID == id &&
                        r.CitizenID == citizenId);


            if (request == null)
            {
                return HttpNotFound();
            }


            if (request.Status !=
                    MunicipalServiceRequestStatus.Paid &&
                request.Status !=
                    MunicipalServiceRequestStatus.ServiceInProgress &&
                request.Status !=
                    MunicipalServiceRequestStatus.Completed)
            {
                TempData["ErrorMessage"] =
                    "The payment receipt is not available at this stage of the request.";

                return RedirectToAction(
                    "Details",
                    "MunicipalServiceRequest",
                    new { id = request.MunicipalServiceRequestID });
            }


            var payment =
                db.Payments
                    .Include("Citizen")
                    .Include("Invoice.MunicipalServiceRequest.ServiceType")
                    .FirstOrDefault(p =>
                        p.CitizenID == citizenId &&
                        p.Status == PaymentStatus.Successful &&
                        p.Invoice != null &&
                        p.Invoice.MunicipalServiceRequestID ==
                            request.MunicipalServiceRequestID);


            if (payment == null)
            {
                TempData["ErrorMessage"] =
                    "No successful payment could be found for this municipal service request.";

                return RedirectToAction(
                    "Details",
                    "MunicipalServiceRequest",
                    new { id = request.MunicipalServiceRequestID });
            }


            return RedirectToAction(
                "Receipt",
                new
                {
                    id = payment.PaymentID
                });
        }


        // ============================================================
        // US154 - VIEW FINANCIAL STATEMENT
        // ============================================================

        [HttpGet]
        public ActionResult FinancialStatement()
        {
            if (Session["CitizenID"] == null)
            {
                return RedirectToAction(
                    "Index",
                    "Login");
            }

            int citizenId =
                (int)Session["CitizenID"];


            var citizen =
                db.Citizens
                    .AsNoTracking()
                    .FirstOrDefault(c =>
                        c.CitizenID == citizenId);


            if (citizen == null)
            {
                return RedirectToAction(
                    "Index",
                    "Login");
            }


            var invoices =
                db.Invoices
                    .Include("MunicipalServiceRequest.ServiceType")
                    .Where(i =>
                        i.MunicipalServiceRequest != null &&
                        i.MunicipalServiceRequest.CitizenID ==
                            citizenId)
                    .AsNoTracking()
                    .ToList();


            var payments =
                db.Payments
                    .Include("Invoice.MunicipalServiceRequest.ServiceType")
                    .Where(p =>
                        p.CitizenID == citizenId)
                    .AsNoTracking()
                    .ToList();


            var refunds =
                db.Refunds
                    .Include("Payment")
                    .Include("Invoice.MunicipalServiceRequest.ServiceType")
                    .Where(r =>
                        r.Payment != null &&
                        r.Payment.CitizenID == citizenId)
                    .AsNoTracking()
                    .ToList();


            var model =
                new CitizenFinancialStatementViewModel
                {
                    StatementGeneratedDate =
                        DateTime.Now,

                    CitizenName =
                        citizen.FirstName +
                        " " +
                        citizen.LastName,

                    InvoiceCount =
                        invoices.Count,

                    PaymentCount =
                        payments.Count(p =>
                            p.Status ==
                            PaymentStatus.Successful),

                    RefundCount =
                        refunds.Count(r =>
                            r.Status ==
                            RefundStatus.Refunded),

                    TotalInvoiced =
                        invoices
                            .Where(i =>
                                i.Status !=
                                InvoiceStatus.Cancelled)
                            .Sum(i => i.Amount),

                    TotalSuccessfulPayments =
                        payments
                            .Where(p =>
                                p.Status ==
                                PaymentStatus.Successful)
                            .Sum(p => p.Amount),

                    TotalRefunded =
                        refunds
                            .Where(r =>
                                r.Status ==
                                RefundStatus.Refunded)
                            .Sum(r => r.Amount)
                };


            // ========================================================
            // BUILD STATEMENT TRANSACTIONS
            // ========================================================

            foreach (var invoice in invoices)
            {
                if (invoice.Status ==
                    InvoiceStatus.Cancelled)
                {
                    continue;
                }


                var request =
                    invoice.MunicipalServiceRequest;

                var serviceName =
                    request != null &&
                    request.ServiceType != null
                        ? request.ServiceType.ServiceName
                        : "Municipal Service";


                model.Transactions.Add(
                    new CitizenFinancialStatementRowViewModel
                    {
                        Date =
                            invoice.IssueDate,

                        Type =
                            "Invoice",

                        Reference =
                            invoice.InvoiceNumber,

                        Description =
                            serviceName,

                        Status =
                            invoice.Status.ToString(),

                        Debit =
                            invoice.Amount,

                        Credit =
                            0m,

                        PaymentID =
                            null,

                        HasReceipt =
                            false
                    });
            }


            foreach (var payment in payments)
            {
                if (payment.Status !=
                    PaymentStatus.Successful)
                {
                    continue;
                }


                bool hasReceipt =
                    db.Receipts.Any(r =>
                        r.PaymentID ==
                        payment.PaymentID);


                model.Transactions.Add(
                    new CitizenFinancialStatementRowViewModel
                    {
                        Date =
                            payment.PaymentDate,

                        Type =
                            "Payment",

                        Reference =
                            payment.TransactionReference,

                        Description =
                            payment.Invoice != null
                                ? payment.Invoice.InvoiceNumber
                                : "Municipal Payment",

                        Status =
                            payment.Status.ToString(),

                        Debit =
                            0m,

                        Credit =
                            payment.Amount,

                        PaymentID =
                            payment.PaymentID,

                        HasReceipt =
                            hasReceipt
                    });
            }


            foreach (var refund in refunds)
            {
                if (refund.Status !=
                    RefundStatus.Refunded)
                {
                    continue;
                }


                model.Transactions.Add(
                    new CitizenFinancialStatementRowViewModel
                    {
                        Date =
                            refund.ProcessedDate ??
                            refund.RequestDate,

                        Type =
                            "Refund",

                        Reference =
                            refund.RefundReference,

                        Description =
                            refund.Invoice != null
                                ? refund.Invoice.InvoiceNumber
                                : "Municipal Refund",

                        Status =
                            refund.Status.ToString(),

                        Debit =
                            refund.Amount,

                        Credit =
                            0m,

                        PaymentID =
                            null,

                        HasReceipt =
                            false
                    });
            }


            // ========================================================
            // RUNNING BALANCE
            // ========================================================

            var chronologicalTransactions =
                model.Transactions
                    .OrderBy(t => t.Date)
                    .ThenBy(t => t.Type)
                    .ToList();


            decimal runningBalance = 0m;


            foreach (var transaction in
                     chronologicalTransactions)
            {
                runningBalance +=
                    transaction.Debit -
                    transaction.Credit;

                transaction.RunningBalance =
                    runningBalance;
            }


            model.Transactions =
                chronologicalTransactions
                    .OrderByDescending(t => t.Date)
                    .ThenByDescending(t => t.Type)
                    .ToList();


            model.CurrentBalance =
     runningBalance;


            return View(model);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}